### ISSUE TITLE
connecting

### ISSUE THREAD

**Issue by WarrioR151** [gekware/minecraft-server-hibernation-pterodactyl-egg#11]
Hi, sometimes it don't connect, or connecting very, very long

https://imgur.com/a/DbV7LNh

how can i fix that?

**Comment by gekigek99** [comment]
it was a bug discussed in [issue 197](https://github.com/gekware/minecraft-server-hibernation/issues/197)

it was fixed [here](https://github.com/gekware/minecraft-server-hibernation/commit/a670db43b9ae17ef2a3fbdc638e9e4b6e575e30a)
