### ISSUE TITLE
Server is not starting cant find why

### ISSUE THREAD

**Issue by roroleroh** [gekware/minecraft-server-hibernation-pterodactyl-egg#16]
Hello
im running on the paper version and i have 2 problems

1.  "msh-config.json" is empty by default can you add "{}" so it'll stop crashing
2.  can you add an eula.txt file and put it on true by default or just create an eula.txt file ? 

thank you for the project !

**Comment by roroleroh** [comment]
also now the server is not detecting when a player is trying to join 
![image](https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/assets/96704503/f181815c-af18-4fe4-b9b4-5dadc3b4c5c6)
![image](https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/assets/96704503/03606c13-76dc-43ad-9c91-fc647b6ee22a)
![image](https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/assets/96704503/3544031b-9d07-4850-947a-7626dbec680b)

**Comment by BolverBlitz** [comment]
> "msh-config.json" is empty by default can you add "{}" so it'll stop crashing

Its not empty by default. The install script is downloading a fresh prefilled file.
```sh
if [ ! -f msh-config.json ]; then
    echo -e "Downloading MSH msh-config.json"
    curl -o msh-config.json https://gist.githubusercontent.com/BolverBlitz/fa895e8062fcab7dd7a54d768843a261/raw/7224a0694a985ba1bff0b4fe9b44f2c79e9b495e/msh-config.json
fi
```

> can you add an eula.txt file and put it on true by default or just create an eula.txt file ?

We cant set it to true by default. But its generated automaticly when you run msh the first time (assuming your msh-config is correct) because it checks if the file exists and if not, it starts minecraft to generate it.

About the images:
Fix the startup command in msh-config file, and it will start.

**Comment by roroleroh** [comment]
Okeyy I'll try once I get home for the install script

For the eula thing I want to start a free hosting kinda thing so it'll be easier if it's true by default is it that hard to change it ?

**Comment by BolverBlitz** [comment]
The egg supports the EULA Popup when you first run the server, if you use a loglevel where you can see the minecraft servers logs.

Its not hard to autoaccept the eula, but its not supposted to be. its the ENDUSER Lizenz, so the user should accept it. If not, then whatever the user does, becomes your problem.

**Comment by roroleroh** [comment]
ok understood and where can i change the default startup command while creating a server i cant find it

**Comment by BolverBlitz** [comment]
Its created by pterodactyl.
Egg Config:
![grafik](https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/assets/35345288/097dfce2-6a1f-4966-8108-8cdcee110d19)

**Comment by roroleroh** [comment]
ty
