### ISSUE TITLE
"MSH is out of date", is there an auto updater?

### ISSUE THREAD

**Issue by snaildos** [gekware/minecraft-server-hibernation-pterodactyl-egg#2]
In the title ^^.

**Comment by BolverBlitz** [comment]
There isn't an auto Uupdater yet. 
Thank you for this issue, we are currently working on a better system to verify versions this might be added. I can at least add it to this egg

**Comment by snaildos** [comment]
👍 Sounds good!
Thank you.

**Comment by BolverBlitz** [comment]
I´m sorry, i just realized that @gekigek99 modifyed the config file, again... I´ll work on that now.

It will stay 2.4.1 (2.4.0 is latest stable) so you are on the latest version.

For 2.4.4 i need to see how it woks.

**Comment by cicatrice74** [comment]
I really like this project, i'm going to try it out, please keep this updated !

**Comment by gekigek99** [comment]
The pterodactyl egg is the best way of autoupdating msh (there were some problems with the change of config but they'll soon be fixed). The egg updates to the version that's on the [ebg server](https://ebg.pw).

Or even a docker container might do the job...
I know that it exist [here](https://github.com/lubocode/minecraft-server-hibernation) (but i don't advise it as it's not very maintained)

Anyway, in this moment i'm developing on msh a new suspension feature for the minecraft server (in branch feature/suspend-ms) and I'm focused on releasing v2.5.0

@cicatrice74 as of now I'm not really planning on implementing an autoupdate feature in msh as there are many feature i want to add first and the autoupdate is handled pretty well with this ptero egg.

**Comment by BolverBlitz** [comment]
As @gekigek99 said. The egg already updates msh (if you click reinstall server, like you do with a lot of other eggs) to the latest version that my server provides, or to the version your server provides (download URL Variable).

Note that the config generator isn´t ready for anything newer than 2.4.2. 
We are working on 2 new things and once they are complete, i hope to update the egg to 2.5.0 but so far 2.4.2 - 2.4.5 dosn´t have too many modifications and all are "pre builds" so i think it dosn´t make a lot of sense to write a config generator for them.

**Comment by snaildos** [comment]
Many users dont reinstall the server and instead it should use a docker image with msh installed in it so it can be easily updated.

**Comment by gekigek99** [comment]
@cicatrice74 @snaildos 

msh can be easily updated using the new [msh egg](https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg)
