### ISSUE TITLE
MSH terminates the server without stop command

### ISSUE THREAD

**Issue by BolverBlitz** [gekware/minecraft-server-hibernation-pterodactyl-egg#5]
If you stop the egg, it will currently kill minecraft instat of running the stop command.

![grafik](https://user-images.githubusercontent.com/35345288/161962423-97af58f9-75bb-4cf7-a5ca-40a3e432d098.png)

I tryed at normal linux, and it works there. Looks like a pterodactyl thing but stop just sends STRG-C.

**Comment by gekigek99** [comment]
You mean sigint?

I solved a similar error some time ago... Maybe this issue was also fixed.

If you need i can specify the issue and commit.

What is ptero using to stop the server?
Is it configurable in the egg?

**Comment by gekigek99** [comment]
Are there updates on this?

I also noticed that ptero stops msh pretty badly (possibly even without saving the world)

**Comment by gekigek99** [comment]
probably discussed in https://github.com/gekware/minecraft-server-hibernation/issues/173

probably fixed in https://github.com/gekware/minecraft-server-hibernation/commit/ec65faddeabc32d9d4f39bc490b32c7ac950ae0f
