### ISSUE TITLE
error after clean install of egg

### ISSUE THREAD

**Issue by cicatrice74** [gekware/minecraft-server-hibernation-pterodactyl-egg#6]
i have this error after clean install

```container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Digest: sha256:da669fc7b63f0f4eb1079a9a8c843a72a202310a8499552041ede5fd25cc1aa3 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
container@pterodactyl~ ./msh_server.bin -port 25568 -d 3 -infohibe Currently not working -infostar Currently not working -file server.jar -allowKill 30 -timeout 120 -msparam "-Xms128M -Xmx1024M"
╔═════════════════════════════════════════════╗
║  _ __ ___  ___| |__                         ║
║ | '_ ` _ \/ __| '_ \                        ║
║ | | | | | \__ \ | | | v2.4.6                ║
║ |_| |_| |_|___/_| |_| 3b66f16               ║
║ Copyright (C) 2019-2022 gekigek99           ║
║ github: https://github.com/gekigek99        ║
║ remember to give a star to this repository! ║
╚═════════════════════════════════════════════╝
2022/04/06 18:45:36 [info  *   ] checking OS support...
2022/04/06 18:45:36 [info  *   ] loading config...
2022/04/06 18:45:36 [error *   ] main: LoadConfig: loadDefault: machineid: machineid: open /etc/machine-id: no such file or directory
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.```

**Comment by BolverBlitz** [comment]
A quick fix is to use the j9 version.

I´ll ask on the pterodactyl discord why this could be. Thanks.

**Comment by cicatrice74** [comment]
Any news on the issue ? I would like to test it.

**Comment by BolverBlitz** [comment]
No, they didn't reply. I'll ask again later.

**Comment by cicatrice74** [comment]
It doesn't function anymore, tried clean installations, but nothing... please try to finally fix this, i would like to test it out on my system but cannot use it anymore...
i'm trying to setup a velocity proxy to turn on a mc server but settings are all fixed... not good at all at this point.
old version was functioning but i need a functional configurable version with ports configurables, messages. please fix asap.
I really love this project

**Comment by BolverBlitz** [comment]
Did you try the J9 egg i toled you?
https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/blob/main/egg-paper-on-demand-j9.json

**Comment by cicatrice74** [comment]
Yes, that have more problems, cannot regularly start it by proxy, it doesn't start when you try connecting if you don't cancel the connection first.. it then disconnects if the server finally starts... i think u should fix something there too, old version was functioning, can u tell how the msh_server.bin is created, can u let it be edited somehow ? There is this strange machine-id error... why ?

**Comment by BolverBlitz** [comment]
> Yes, that have more problems, cannot regularly start it by proxy, it doesn't start when you try connecting if you don't cancel the connection first.. it then disconnects if the server finally starts...

This only happens because the Client thinks its a diffrent Version, you can just set the config manualy.
msh-config.json
```json
"Version": "Paper 1.18.2",
"Protocol": 758
```

But once you joined, the config is updated and from then it will perfectly: (Screenshot)
![grafik](https://user-images.githubusercontent.com/35345288/162582224-c846ac41-a7a4-409c-ac8a-c51f4a77f51e.png)


> i think u should fix something there too, old version was functioning

Maybe @gekigek99 can do that. Current issue: You join with 1.18.2 client to MSH beeing 1.17.2 and you won´t get the "Starting" kick. You just timeout. MSH only starts when you click "Cancel" in the client.

> can u tell how the msh_server.bin is created

Its downloaded from a server (URL in EGG Variables)
```sh
curl -o msh_server.bin ${MSH_D_URL}
```

> can u let it be edited somehow

Sure you can edit it, just fork our repo and make your modifications. [MSH](https://github.com/gekware/minecraft-server-hibernation) then build it, upload it to a webserver where the egg can then download it from. 

> There is this strange machine-id error... why ?

This error dosn´t exists in J9. 
MSH generates a id thats required to check the version of msh (Dev, Release, Depricated). The machine-id file is on every linux system at the same location with a unique value. For some reason it dosn´t exist in the pterodactyl hotspot java egg :/ 
So far nobody of the devs toled me why, or even responded to it.

**Comment by BolverBlitz** [comment]
I made a issue. [Pterodactyl](https://github.com/pterodactyl/panel/issues/4043)

**Comment by BolverBlitz** [comment]
So i would sugest to follow his [advice](https://github.com/pterodactyl/panel/issues/4043#issuecomment-1094122884) and add another startup parameter to msh for maschine-id, if this is given msh should not try to read the ID. @gekigek99

**Comment by gekigek99** [comment]
> i think u should fix something there too, old version was functioning

@cicatrice74 can you tell me what version/commit you are using? and what was the one that was functioning?

> So i would sugest to follow his https://github.com/pterodactyl/panel/issues/4043#issuecomment-1094122884 and add another startup parameter to msh for maschine-id, if this is given msh should not try to read the ID. @gekigek99

@BolverBlitz isn't it possible, when an egg is installed to generate a file with a randomized sha1 in `/etc/machine-id` of the container? so that the container generates it's own id (even better if keeps it after reinstallation)
_(otherwise i'll leave it empty in config by default and try to get it with machineid... if it fails i generate a random one and write that to config)_

**Comment by cicatrice74** [comment]
I had the 2.4.0 version, it was almost ok, needed some custom or pterodactyl parameters' related issue...
I am trying to have this finally fully working but with no success, it would be great to have start parameters directly tanken from the pterodactyl server section... maybe some sort of plugin support for the "waiting" server (tcpshield remember?), and fix the needing of cancel connection for the server to start.
There are lot of problems in this latest version...
I don't like the config section inside the msh_config file... i do not underrstand the 2555 port inside of it.
Make it more simple like
Server_Name: name
Server_sleeping_port: 25568
Server_port: {get it from the pterodactyl panel server created}
Memory_for_sleeping: 256M
Memory: {get it from the pterodactyl panel server created}

**Comment by BolverBlitz** [comment]
The egg currently isnt nstalling 2.4.0 of MSH, its installing 2.4.6
For 2.4.0 you need the legacy egg.

**Comment by gekigek99** [comment]
@cicatrice74 

> maybe some sort of plugin support for the "waiting" server (tcpshield remember?), and fix the needing of cancel connection for the server to start.
There are lot of problems in this latest version...
I don't like the config section inside the msh_config file... i do not underrstand the 2555 port inside of it.
Make it more simple like
Server_Name: name
Server_sleeping_port: 25568
Server_port: {get it from the pterodactyl panel server created}
Memory_for_sleeping: 256M
Memory: {get it from the pterodactyl panel server created}

Feel free to pr ;)

**Comment by BolverBlitz** [comment]
> I don't like the config section inside the msh_config file...

Luckily, you don´t need open it at all.
I can currently not see any problem, thats not in the readme already.

Full, clean install of the Egg.
https://www.youtube.com/watch?v=vd_kPn1mf8s

**Comment by cicatrice74** [comment]
I was trying to help you telling you what's wrong with this, if i was able to "pr" i would make something probably better... maybe i'm trying to help wrong programmers. bye. will never use this. anymore

**Comment by cicatrice74** [comment]
It is not serious to remove my comment after you have exaggerated yours towards me, really not very serious

**Comment by gekigek99** [comment]
@cicatrice74 i won't delete this issue for future reference but if you have any concern you are welcome to contact me on discord to have a clear explanation on the matter.

**Comment by gekigek99** [comment]
the initial error was fixed [here](https://github.com/gekware/minecraft-server-hibernation/commit/962319b7530dc61e1e60f10a0a92e6587d82a449)

now it needs to be implemented in the egg
