### ISSUE TITLE
Crash: ELF@_: not found

### ISSUE THREAD

**Issue by dominik-korsa** [gekware/minecraft-server-hibernation-pterodactyl-egg#7]
I'm getting an issue after creating a server with this egg (both the j9 and normal versions). The server crashes immediately after each server restart

[paper-on-demand-logs.txt](https://github.com/gekware/minecraft-server-hibernation-pterodactyl-egg/files/9101592/paper-on-demand-logs.txt)

```
container@pterodactyl~ ./msh_server.bin -port 25565 -d 3 -infohibe Currently not working -infostar Currently not working -file server.jar -allowKill 30 -timeout 30 -msparam "-Xms128M -Xmx0M"
./msh_server.bin: 1: ELF@_: not found
./msh_server.bin: 2: Syntax error: "(" unexpected
```

I'm running wings on `Canonical-Ubuntu-22.04-aarch64-2022.06.16-0`

**Comment by BolverBlitz** [comment]
Thanks for the issue, i think i know the problem. 
Just need to setup a ARM server to test.
