### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by WarrioR151** [gekware/minecraft-server-hibernation-pterodactyl-egg#9]
Hey, hi.. what is WAIT TIME FOR SHUTDOWN variable for?  When user can edit msh-config.json and set how much time he want? I want hosting (free) that will stop servers without players, this one looks very very cool.. but not work as needed, user can just edit msh-config.json and can have their server online how much he want :/ 

Can i prevent it somehow?

**Comment by BolverBlitz** [comment]
what is WAIT TIME FOR SHUTDOWN variable for?
> It exists so a admin (Host Owner) can set the time it takes from 0 players dedected until the server will be stoped

When user can edit msh-config.json and set how much time he want?
> Yes, they can edit the config but the startparameter is always more important to msh

**Comment by WarrioR151** [comment]
Hey, thanks for fast answer, but i need user to not edit msh config, because user can set whatever time he want, so he can set for example stop time to 10000000 seconds, then it completely ignore that 120 second set in startup paramater, and user have 1000000000 seconds, if you understand what i mean, i'm making free server hosting, and i need to shutdown servers that are no players online, and start when someone join, but here user can just edit stop time and can have server running 24/7 taking my resources, i need to know if i can prevent from it

**Comment by gekigek99** [comment]
the egg start parameter ovverrides msh-config,json files, and the user cannot modify the egg start parameter.
